package seedu.wildwatch.error;

public enum InvalidInputErrorType {
    EMPTY_INPUT,
    EMPTY_ADD_INPUT,
    EMPTY_DELETE_INPUT,
    EMPTY_FIND_INPUT,
    EMPTY_LIST,
    ENTRY_NOT_FOUND,
    INVALID_DATE,
    INVALID_DELETE_INDEX,
    INVALID_FIND_QUERY,
    INVALID_EDIT_INPUT,
    INVALID_INPUT,
    UNKNOWN_INPUT,
    CUSTOM
}
